### ISSUE TITLE
Debugging custom taglibs

### ISSUE THREAD

**Issue by kristianmandrup** [marko-js/marko#131]
I'm writing a huge set of taglibs to wrap all of Semantic UI. 
Problem is that if I/when make any mistake, no taglibs seem be loaded and no errors are shown in the console either. 

I'm trying to heavily leverage taglib imports:

```js
{
  "tags-dir": ".",
  "taglib-imports": [
    "./list/marko-taglib.json"
  ]  
}
```

In my real scenario, there would be ~20 taglibs imported.
Is there a way to turn on some kind of debugging, logging of how marko resolves the taglibs and where it gives up? This is becoming a real PAIN to me :(
Thanks :)

**Comment by kristianmandrup** [comment]
I tried cloning marko, npm linking it and then inserting debug statements...

```sh
Marko appplication ready on port 4000
[browser-refresh] Server is ready. Watching files for changes.
[browser-refresh] Triggering refresh of client pages...
[browser-refresh] Refresh triggered
page state { title: 'Repo manager',
  header: 'Repo manager',
  content: 'Hello',
  lists: { users: [ [Object], [Object] ] } }
template data { title: 'Repo manager',
  header: 'Repo manager',
  content: 'Hello',
  lists: { users: [ [Object], [Object] ] } }
rendering template: /Users/kristianmandrup/repos/test123/repo-manager-v3/apps/index/page/index.marko
state: { title: 'Repo manager',
  header: 'Repo manager',
  content: 'Hello',
  lists: { users: [ [Object], [Object] ] },
  '$global': 
   { menus: { main: [Object], session: [Object] },
     lists: { repos: [Object], teams: [Object], users: [Object] },
     feeds: { activity: [Object] },
     appName: 'Repo Manager v3' } }
loadTagLib /Users/kristianmandrup/repos/markoa/marko/taglibs/core/marko-taglib.json
loadTagLib /Users/kristianmandrup/repos/markoa/marko/taglibs/html/marko-taglib.json
loadTagLib /Users/kristianmandrup/repos/markoa/marko/taglibs/caching/marko-taglib.json
loadTagLib /Users/kristianmandrup/repos/markoa/marko/node_modules/marko-layout/marko-taglib.json
loadTagLib /Users/kristianmandrup/repos/markoa/marko/node_modules/marko-async/marko-taglib.json
```

But my own custom taglibs are NEVER loaded it seems?

```js
    tagsDir: function(dir) {
        // The "tags-dir" property is used to supporting scanning
        // of a directory to discover custom tags. Scanning a directory
        // is a much simpler way for a developer to create custom tags.
        // Only one tag is allowed per directory and the directory name
        // corresponds to the tag name. We only search for directories
        // one level deep.
        var taglib = this.taglib;
        var path = this.path;
        var dirname = this.dirname;
        // TAGLIB DIR
        console.log('tagsDir', dir);
        if (Array.isArray(dir)) {
            for (var i = 0; i < dir.length; i++) {
                scanTagsDir(path, dirname, dir[i], taglib);
            }
        } else {
            scanTagsDir(path, dirname, dir, taglib);
        }
    },

    taglibImports: function(imports) {
        // The "taglib-imports" property allows another taglib to be imported
        // into this taglib so that the tags defined in the imported taglib
        // will be part of this taglib.
        //
        // NOTE: If a taglib import refers to a package.json file then we read
        //       the package.json file and automatically import *all* of the
        //       taglibs from the installed modules found in the "dependencies"
        //       section
        var taglib = this.taglib;
        var dirname = this.dirname;
        var importPath;
        var resolveFrom = require('resolve-from');
        // ITERATE
        console.log('imports', imports);
        if (imports && Array.isArray(imports)) {
            for (var i=0; i<imports.length; i++) {
                var curImport = imports[i];
                // CURRENT
                console.log('import', curImport);
                if (typeof curImport === 'string') {

                    } else {
                        importPath = resolveFrom(dirname, curImport);
                        // ADDED
                        console.log('taglib.addImport', importPath);
                        taglib.addImport(importPath);
                    }
...
```

Please provide much better documentation on this feature and guidance on how to debug issues with resolution of tags and taglibs.

**Comment by kristianmandrup** [comment]
I simply don't understand how to interpret the documentation on this. Does marko ONLY use the first `marko-taglib.json` it encounters as it travels up the path, or does it resolve all taglibs that it finds on its way? What if multiple taglibs import the same other taglibs? etc. etc?

In my scenario I have the following structure:

```sh
apps
  /_global
    /components
      /list
        /ui-list (tag)
          template.marko
          ...
       marko-taglib.json `tags-dir: '.'`
    marko-taglib.json `taglib-imports: [ './list/marko-taglib.json', ...]`
 marko-taglib.json `taglib-imports: [ './components/marko-taglib.json']`  
  
  /index
   /components
     ...
    /page
     index.marko (references `ui-list` tag)
   marko-taglib.json `tags-dir: './components'`
```

Should I also reference the global taglib from the index taglib, or will it auto-resolve as it goes up?
I had it working until I introduced the extra level in the components folder in order to group tags by type/category. Why!? Im lost...

**Comment by kristianmandrup** [comment]
Looks like the problem is in part caused by using `browser-refresh` :O
With some more debugging in the taglibs compiler (which is in BIG NEED of REFACTORING!!!)

```sh
taglib lookup: buildLookup /Users/kristianmandrup/repos/test123/repo-manager-v3/apps/_global/components/icon-item
tryDir /Users/kristianmandrup/repos/test123/repo-manager-v3/apps/_global/components/icon-item/marko-taglib.json
tryDir /Users/kristianmandrup/repos/test123/repo-manager-v3/apps/_global/components/marko-taglib.json
tryDir /Users/kristianmandrup/repos/test123/repo-manager-v3/apps/_global/marko-taglib.json
tryDir /Users/kristianmandrup/repos/test123/repo-manager-v3/apps/marko-taglib.json
tryDir /Users/kristianmandrup/repos/test123/repo-manager-v3/marko-taglib.json
tryDir /Users/kristianmandrup/repos/test123/marko-taglib.json
tryDir /Users/kristianmandrup/repos/marko-taglib.json
tryDir /Users/kristianmandrup/marko-taglib.json
tryDir /Users/marko-taglib.json
tryDir /marko-taglib.json
taglib lookup: buildLookup /Users/kristianmandrup/repos/test123/repo-manager-v3/apps/_global/components/ui-icon
tryDir /Users/kristianmandrup/repos/test123/repo-manager-v3/apps/_global/components/ui-icon/marko-taglib.json
tryDir /Users/kristianmandrup/repos/test123/repo-manager-v3/apps/_global/components/marko-taglib.json
tryDir /Users/kristianmandrup/repos/test123/repo-manager-v3/apps/_global/marko-taglib.json
tryDir /Users/kristianmandrup/repos/test123/repo-manager-v3/apps/marko-taglib.json
tryDir /Users/kristianmandrup/repos/test123/repo-manager-v3/marko-taglib.json
tryDir /Users/kristianmandrup/repos/test123/marko-taglib.json
tryDir /Users/kristianmandrup/repos/marko-taglib.json
tryDir /Users/kristianmandrup/marko-taglib.json
tryDir /Users/marko-taglib.json
tryDir /marko-taglib.json
```

**Comment by kristianmandrup** [comment]
My conclusion so far: You can only import at ONE level. You CANNOT currently have a taglib which imports a taglib which imports yet another taglib. But WHY this LIMIT!? Is just a basic recursive model...

**Comment by kristianmandrup** [comment]
By going through the code I can see that it seems it is not currently setup to allow this. It assumes any imported taglib is a "leaf" taglib apparently...

```js
exports.loadTaglib = function(path) {
    console.log('loadTagLib', path);
    var taglibProps = taglibReader.readTaglib(path);

    var taglib = new Taglib(path);
    taglib.addInputFile(path);
```

I'm completely baffled!!! This ruins my whole design... I simply can't believe it. Please help me resolve this bug ASAP. Thanks :)

**Comment by patrick-steele-idem** [comment]
First off, it's all just code so we can make anything work :) I don't see anything here to suggest that you would need a difficult change and I would be surprised if second-level imports are not supported. If that is the case then we should fix it. I'll add a test case and see what I can figure out.

Also, can you please clarify on the following?:

> Looks like the problem is in part caused by using browser-refresh

What makes you think that?

**Comment by kristianmandrup** [comment]
Was a hunch. But no. However I ran into a caching issue as well. If I had a taglib, importing another taglib which referenced a tag dir, the final taglib did not resolve until I inserted a space in that taglib and saved.

**Comment by kristianmandrup** [comment]
Thanks :) Please make a test case to cover my issue. I would love to help out myself. This is bugging me down...

**Comment by kristianmandrup** [comment]
I just sent you a zip with a fixture for this scenario.

**Comment by patrick-steele-idem** [comment]
Great. Thank you. I'll take a look now.

**Comment by kristianmandrup** [comment]
and here my attempt at testing taglib imports (currently NO test coverage)

`taglib-imports-test.js`

```js
'use strict';
var chai = require('chai');
chai.Assertion.includeStack = true;
require('chai').should();
var expect = require('chai').expect;
var nodePath = require('path');

describe('taglib-lookup' , function() {

    beforeEach(function(done) {
        for (var k in require.cache) {
            if (require.cache.hasOwnProperty(k)) {
                delete require.cache[k];
            }
        }

        done();
    });

    it('should lookup taglibs with nested-import', function() {
      var taglibLookup = require('../compiler').taglibs.lookup;
      var lookup = taglibLookup.buildLookup(nodePath.join(__dirname, 'fixtures/nested-import'));
      console.log('lookup', lookup);
      // NOT SURE WHAT TO TEST FOR FROM HERE
    });
});
```

**Comment by patrick-steele-idem** [comment]
Thanks for the sample project, @kristianmandrup. I was able to reproduce the problem pretty quickly and I have put in a fix. New version published: `marko@2.7.14`

Let me know if you see any other issues. Thanks again!

**Comment by kristianmandrup** [comment]
Awesome! I can hardly believe it :) Thanks a million @patrick-steele-idem :)

**Comment by kristianmandrup** [comment]
Would be even better if there was a way to add some kind of basic logging for taglib and tag resolution somehow ;)

**Comment by kristianmandrup** [comment]
I tried it out. Still doesn't work. In my case, for some reason it never even calls `handleImports`.
I added a console log directly to the `node_modules/marko/compiler/taglibs/taglib-lookup.js`

Seems like marko "stalls" before ever starting to resolve even my first taglib, never ever calling `tagDir` for some reason :( And this stalling only occurs when I have nested taglibs like in the example I sent. Strange indeed!

**Comment by patrick-steele-idem** [comment]
:+1: on logging. The [debug](https://github.com/visionmedia/debug) module would probably be the most appropriate since you could launch the app with `DEBUG=marko node server.js` to see exactly what marko is doing during compilation. Do you mind opening a separate Github issue to describe what type of logging you would be interested in for marko?

**Comment by patrick-steele-idem** [comment]
@kristianmandrup, please try the following:

```
MARKO_CLEAN=true node your-app.js
``` 

That will force all templates to be recompiled.

**Comment by kristianmandrup** [comment]
Thanks. Just tried it. Still same problem.

**Comment by patrick-steele-idem** [comment]
Do you see any issue with the test case I added? It was pretty much your code with some extra things removed and the test cases are passing.

Do you by any chance have a circular dependency in your imports?

**Comment by patrick-steele-idem** [comment]
I just pushed a small change to handle circular imports, but I don't think that is impacting you because otherwise you would have seen a 'Maximum call stack` error. Here's the fix I pushed: https://github.com/marko-js/marko/commit/608d9092bbc71ac5e79a0b8c0ec15d9de88698b3

**Comment by kristianmandrup** [comment]
I have the exactly the setup I described above.

A page `index.marko` referencing a tag `icon-list`
Then a `marko-taglib.json` in parent folder referencing "internal" taglib to the page via `tags-dir`, then one level further up, a taglib, importing the global components via `taglib-imports`. From here it gets tricky. 
In `global/components/marko-taglib.json`, if I only use `tags-dir` everything "just works". However if I use `taglib-imports`, the lookup only looks up the pre-registered taglibs and never even attempts to find my own taglibs.

```js
function buildLookup(dirname) {
  var taglibs = taglibFinder.find(dirname, exports.registeredTaglibs);
  ...
```

Never goes beyond `exports.registeredTaglibs` for some reason!?

**Comment by patrick-steele-idem** [comment]
Is your app crashing?

Do you think you would be able to provide a fork of marko with a failing test case?

**Comment by kristianmandrup** [comment]
Not crashing, just never trying to resolve any tag libs not pre-registered. 
PS: How would I preregister my own taglibs? Perhaps better/easier to use the `package.json` import strategy? They are global components after all...

**Comment by patrick-steele-idem** [comment]
Are those global imports in an installed node module?

**Comment by kristianmandrup** [comment]
no, all is local. I'm using latest master. `buildLookup` is never called.

```js
function buildLookup(dirname) {
	console.log('buildLookup', dirname);
```

**Comment by patrick-steele-idem** [comment]
If `buildLookup()` is not being called then that would suggest that no templates are being compiled. Make sure you run your app with `MARKO_CLEAN=true node app.js` to force all templates to be recompiled.

**Comment by kristianmandrup** [comment]
Yeah, I run with `MARKO_CLEAN=true node .` each time. Neither `compile` nor `compileFile` of `marko-compiler.js` are being called :P

**Comment by kristianmandrup** [comment]
But when I move my `icon-list` tag up to the next level of tag libs (ie. not nested anymore) - everything works again, template is compiled etc:

Problem is when I put my template at

`apps/_global/components/list/ui-icon/template.marko`

ie. inside `list` folder. I wonder if somehow list is a reserved name or sth very strange?!

```sh
createCompiler /Users/kristianmandrup/repos/test123/repo-manager-v3/apps/_global/components/ui-icon/template.marko
TemplateCompiler path /Users/kristianmandrup/repos/test123/repo-manager-v3/apps/_global/components/ui-icon/template.marko
buildLookup /Users/kristianmandrup/repos/test123/repo-manager-v3/apps/_global/components/ui-icon
lookup /Users/kristianmandrup/repos/test123/repo-manager-v3/apps/_global/components/marko-taglib.json,/Users/kristianmandrup/repos/test123/repo-manager-v3/apps/marko-taglib.json,markoa-skeleton-app,browser-refresh-taglib,marko-core,marko-html,marko-caching,marko-layout,marko-async { merged: 
   { path: '/Users/kristianmandrup/repos/test123/repo-manager-v3/node_modules/marko/node_modules/marko-async/marko-taglib.json',
```

**Comment by kristianmandrup** [comment]
How can we make a test for this?

**Comment by kristianmandrup** [comment]
```js
if (process.env.MARKO_CLEAN === '' || process.env.MARKO_CLEAN === 'true') {
    defaultOptions.checkUpToDate = false;
}
```

So the problem could be in this "up to date" logic I guess?

**Comment by kristianmandrup** [comment]
It operates on taglibs to determine if they have been updated...

```js
exports.getLastModified = function(sourceFile, taglibs) {
    var statSource = fs.statSync(sourceFile);
    var lastModifiedTime = statSource.mtime.getTime();
    var taglibFiles = taglibs.getInputFiles();
```

**Comment by patrick-steele-idem** [comment]
The logic for disabling the `checkUpToDate` looks fine to me so `MARKO_CLEAN=true node app.js` should force all templates to be recompiled. Are you sure that is not happening?

**Comment by kristianmandrup** [comment]
Yes, NO templates are compiled when I have nested taglibs for some strange reason... trying to figure out why/where it decided to skip this step.

**Comment by kristianmandrup** [comment]
Doesn't even call `checkUpToDate` :O

```js
 checkUpToDate: function(targetFile) {
    console.log('checkUpToDate', targetFile);
```

**Comment by kristianmandrup** [comment]
What is top level entry point to start compilation or decide whether to compile template?

**Comment by patrick-steele-idem** [comment]
If you are using the Node.js require extension then it will be here:

https://github.com/marko-js/marko/blob/8035b5de72fc8258f88bcccec41e9e8ce0ff4245/node-require.js#L28

**Comment by kristianmandrup** [comment]
Thanks for all your assistance :)
